Metrics/AbcSize:
  Max: 23

Metrics/ClassLength:
  Max: 143

Metrics/LineLength:
  Max: 412

Metrics/MethodLength:
  Max: 14

Style/Documentation:
  Enabled: false

Style/NestedTernaryOperator:
  Enabled: false